### ISSUE TITLE
getting blank screen on startup.

### ISSUE THREAD

**Issue by Gsuz** [boffbowsh/ss_tvos#4]
Last 2 days I've been getting a blank screen on startup. I've resolved the issue by reinstalling and re-entering the login information so the problem is not with the api endpoint. I'm not sure how to troubleshoot this. Any chance the app could be more verbose on startup to see what's up?

**Comment by boffbowsh** [comment]
Sorry, I'm not going to have time to work on this for at least a couple of weeks. Pull Requests welcome though.

**Comment by boffbowsh** [comment]
Added an error message if it can't get feed data
